export enum OccurrenceStatus {
    DRAFT = 'DRAFT',
    PENDING_DRIVER = 'PENDING_DRIVER',
    PENDING_CONTAINER_INFO = 'PENDING_CONTAINER_INFO',
    CONTAINER_COLLECTED = 'CONTAINER_COLLECTED',
    SENT_TO_CONTRACTOR = 'SENT_TO_CONTRACTOR',
    LOADING_SCHEDULED = 'LOADING_SCHEDULED',
    COMPLETED = 'COMPLETED',
  }

  export enum ServiceOrderStatus {
    DRAFT = 'DRAFT',
    PRINTED = 'PRINTED',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
  }

  export enum ContainerStatus {
    PENDING = 'PENDING',
    COLLECTED = 'COLLECTED',
    IN_TRANSIT = 'IN_TRANSIT',
    DELIVERED = 'DELIVERED',
  }