export enum OperationDocumentType {
  CONTAINER_PHOTO = 'CONTAINER_PHOTO',
  PICKUP_TICKET = 'PICKUP_TICKET',
  INVOICE = 'INVOICE',
  CTE = 'CTE',
  MDFE = 'MDFE',
  SIGNED_RECEIPT = 'SIGNED_RECEIPT',
  DELIVERY_TICKET = 'DELIVERY_TICKET',
  DELIVERY_RECEIPT = 'DELIVERY_RECEIPT',
}
